.TH VOLUMECONTROL 1 "July 29, 2004"
.SH NAME
VolumeControl \- audio mixer for GNUstep
.SH SYNOPSIS
.B VolumeControl
.SH DESCRIPTION
This manual page documents briefly the
.B VolumeControl
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBVolumeControl\fP is a GNUstep program for adjusting the audio mixer
on systems that use the ALSA or OSS APIs. It allows the sound level,
left/right speakers, muting for master, PCM, bass, and treble levels
to be controlled.
.SH SEE ALSO
.BR GNUstep (7).
.br
.SH AUTHOR
This manual page was written by G\[:u]rkan Myczko <alex@aiei.ch>,
for the Debian project (but may be used by others).
